Repository palantir/deadlines-java, pull requests merged in 2025-02, with the labels that each got.

#17 Handle invalid durations
  changelog/@unreleased/pr-17.v2.yml
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
  deadlines/src/test/java/com/palantir/deadlines/DeadlinesTest.java
Labels: autorelease, merge when ready

#18 Log `expect-within` header parsing failures
  changelog/@unreleased/pr-18.v2.yml
  deadlines/build.gradle
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
Labels: merge when ready

#20 Deadlines.encodeToRequest checks for existing headers on the request
  changelog/@unreleased/pr-20.v2.yml
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
  deadlines/src/test/java/com/palantir/deadlines/DeadlinesTest.java
Labels: merge when ready

#22 Revert "Deadlines.encodeToRequest checks for existing headers on the request"
  changelog/@unreleased/pr-20.v2.yml
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
  deadlines/src/test/java/com/palantir/deadlines/DeadlinesTest.java
Labels: merge when ready, no changelog

#19 Optimize Deadlines::tryParseSecondsToNanoseconds
  changelog/@unreleased/pr-19.v2.yml
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
  deadlines/src/test/java/com/palantir/deadlines/DeadlinesTest.java
Labels: autorelease, merge when ready

#23 take the ceiling of millis on encoded deadline values
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
  deadlines/src/test/java/com/palantir/deadlines/DeadlinesTest.java
Labels: merge when ready, no changelog

#24 Expand parsing tests
  .gitignore
  build.gradle
  changelog/@unreleased/pr-24.v2.yml
  deadlines/build.gradle
  deadlines/src/test/java/com/palantir/deadlines/DeadlinesTest.java
  versions.lock
  versions.props
Labels: merge when ready

#27 use custom clock for better testing
  deadlines/build.gradle
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
  deadlines/src/test/java/com/palantir/deadlines/DeadlinesTest.java
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#25 add DeadlineExpiredException
  changelog/@unreleased/pr-25.v2.yml
  deadlines-api/build.gradle
  deadlines/build.gradle
  deadlines/src/main/java/com/palantir/deadlines/DeadlineExpiredException.java
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
  deadlines/src/main/java/com/palantir/deadlines/DeadlinesHttpHeaders.java
  deadlines/src/test/java/com/palantir/deadlines/DeadlinesTest.java
  settings.gradle
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#30 encode/decode DeadlineExpiredException types
  changelog/@unreleased/pr-30.v2.yml
  deadlines/src/main/java/com/palantir/deadlines/DeadlineExpiredReasons.java
  deadlines/src/main/java/com/palantir/deadlines/DeadlinesHttpHeaders.java
  deadlines/src/test/java/com/palantir/deadlines/DeadlineExpiredReasonsTest.java
Labels: autorelease, merge when ready

#31 remove Optional allocation in RequestDecodingAdapter#getFirstHeader
  changelog/@unreleased/pr-31.v2.yml
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
  deadlines/src/test/java/com/palantir/deadlines/DeadlinesTest.java
Labels: autorelease, merge when ready
