Repository palantir/deadlines-java, pull requests merged in 2025-03, with the labels that each got.

#42 add ability to disable deadline propagation
  changelog/@unreleased/pr-42.v2.yml
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
  deadlines/src/main/metrics/deadlines-metrics.yml
  deadlines/src/test/java/com/palantir/deadlines/DeadlinesTest.java
Labels: merge when ready

#46 remove RemainingDeadline
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
Labels: merge when ready, no changelog

#47 nit: Use `javax.annotation.Nullable`
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
Labels: autorelease, merge when ready, no changelog

#48 Redundant calls to disablePropagation are a no-op
  changelog/@unreleased/pr-48.v2.yml
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
Labels: autorelease, merge when ready

#51 dont report expired metrics when storing deadlines (take 2)
  deadlines/src/main/java/com/palantir/deadlines/Deadlines.java
  deadlines/src/test/java/com/palantir/deadlines/DeadlinesTest.java
Labels: autorelease, merge when ready, no changelog
